### PR TITLE
Fixed where items could not be moved to storage in armor-rack mod

### PR DESCRIPTION
**Pull request by RadTuna**
Related mod workshop : https://steamcommunity.com/sharedfiles/filedetails/?id=1875828205&searchtext=armor+rack \
Related mod github : https://github.com/khamenman/armor-racks

## Changes 
- Fixed the problem that only the ~Cell code block was executed because TargetB of the if(TargetB.HasThing) code was not initialized
- Create Jobs for multiple items before storage fills up. Because of this, even if Accepts() is false, the second and subsequent Jobs are processed in the same storage. Double-check Accepts() and fix it not to add.
- Remove unnecessary Toils_Goto.GotoCell() code

### CODE REVIEW

**Comment by Angelin01** [comment]
Hey @RadTuna, sorry for messaging on a year and a half old PR. I've pulled your changes into master (for 1.4 compatibility) and they seem to work perfectly fine (minus some mixed indentation, but that's not important). Would you be willing to publish a fork? I'm willing to do it myself, but I have exactly 0 experience modding for Rimworld, which means I probably can't support said fork.

If @Mehni comes back, hopefully he will merge these, but otherwise, for "normal folk", downloading the zip outside of the steam workshop or compiling it like I did are not really viable alternatives.

**Comment by RadTuna** [comment]
Hello @Angelin01, thank you for showing interest in my old PR.
I'm currently not very passionate about Rimworld modding (I only made those changes out of personal convenience in the past), so I don't have any plans to upload a fork version to the Steam Workshop. However, feel absolutely free to take this PR and upload it to the Workshop or use it for personal purposes in any way you see fit.

**Comment by Angelin01** [comment]
@RadTuna I'm so so sorry for poking you again, but I have no idea how to proceed otherwise, aside from trying random things. If you are willing to help me a bit, it seems your patch had an issue that's causing the pawns to pick up and immediately drop items in a loop. I have a save where I can reproduce this, but I've been having a hard time actually reproducing consistently it on a test environment.

I've narrowed down the situation as thus.

`oldHaulDestination` is `null`, this causes us to enter the `if (needRefindDestination)` section.

Then, `if (StoreUtility.TryFindBestBetterNonSlotGroupStorageFor(thing, pawn, pawn.Map, currentPriority, pawn.Faction, out var haulDestination, true))` return false, which makes us drop the item in the else block:

```cs
pawn.carryTracker.innerContainer.TryDrop(thing, ThingPlaceMode.Near, thing.stackCount, out var _);
```

This loops forever as far as I can tell, unless something interrupts the job.

Are there are pointers you could give me? I have no idea how these `TryFindBestBetter` methods work, or what they look for, or what I should expect...

**Comment by RadTuna** [comment]
@Angelin01
First, you'll need to decompile the `TryFindBestBetter...` functions since they are built-in functions in Rimworld. You can refer to this guide (I used ILSpy):
https://rimworldwiki.com/wiki/Modding_Tutorials/Decompiling_source_code

Now, regarding the issue with `oldHaulDestination` becoming null, that's indeed strange. It's a code meant to handle cases where the `Accept()` function originally returns false. The other conditions are defensive code for exceptional situations.

In any case, it seems that removing the `TryDrop` code I added should resolve the problem.

`TargetB` is the destination requested by the previous job, and `TargetC` is the fallback destination. However, if `TargetB` is invalid, it's currently set to just drop the item. Removing this part of the code should allow it to be handled properly in the `if (TargetB.HasThing)` else condition.

**Comment by Angelin01** [comment]
> you'll need to decompile the TryFindBestBetter... functions since they are built-in functions in Rimworld

I was hoping to avoid that, but it seems Rider's decompiler is failing me. Shame.

> Now, regarding the issue with oldHaulDestination becoming null, that's indeed strange. It's a code meant to handle cases where the Accept() function originally returns false.

Agreed, I actually came here hoping you'd have an idea why it would turn null. I was thinking that the cast `IHaulDestination oldHaulDestination = TargetB.Thing as IHaulDestination;` was invalid. I was trying to understand if, for some reason, the changes to other methods where we set pass targetB instead of targetA had a chance of passing along something that is not considered a haul destination, but, once again, that fails me.

> TargetB is the destination requested by the previous job, and TargetC is the fallback destination. However, if TargetB is invalid, it's currently set to just drop the item.

I appreciate this. This has already helped me understand this more than my hours of debugging last night. Thank you.

> In any case, it seems that removing the TryDrop code I added should resolve the problem.

Indeed, they simply carry the one item to the proper location in that case. I'll look around a bit more, see if I can find the root cause, otherwise I'll leave it as is. Thank you very much.

**Comment by Angelin01** [comment]
Unfortunately, it seems removing the `else` block has even worse side effects. Pawns now hoard items around, never dropping them.

image

I guess I have no choice, Imma dig into this. Thanks anyway! You already helped a ton.

**Comment by Mehni** [comment]
@RadTuna Hello and thank you! My apologies for not getting back to you earlier. I shall close your PR without merging, because I've just merged @Angelin01's PR #52.

The good news is that the spirit of your changes and the compatibility with the Armor Rack mod is now a part of PUAH and I wish to thank you once again for your efforts.

**Pull request closed without merging**
