### PR TITLE
Fix issues when hauling to containers + extra improvements

### PR DESCRIPTION
**Pull request by Angelin01**
# Fix issues when hauling to containers + extra improvements

This Pull Request contains a important bug fix to PU&H's behavior when hauling to containers.
It also contains other changes, quite large, but mostly visual in nature, largely contributed by @bbradson [here](https://github.com/bbradson/PickUpAndHaul/commit/603e3f8c16a49630b724f58269258d65b80a6557).

To try and help the review process, I recommend a review on a _commit per commit_ basis. I'll try to explain the changes that way too to facilitate the review, as some commits can get quite large even though the end result is of a reasonable size.

## The Bug

The bug in question is quite simple and easy to reproduce: pawns will grab an item, drag it to the container "Armor Racks" in this case, and constantly place it on the ground and pick it up again, in a loop, never placing it onto the container itself.

---

### [Edit editorconfig to match code style (c79c5a1)](https://github.com/Mehni/PickUpAndHaul/commit/c79c5a196b347ceca3f749183d68e44574043eb8)

I believe at some point, either through accident or on purpose, the code was changed to use tabs instead of spaces. I've reflected this change on the .editorconfig file to avoid ruining the history even more.

---

### Commits [31ea348](https://github.com/Mehni/PickUpAndHaul/commit/31ea3481f350f7aeea3c10dc6550b2aee4ca28be), [fd3d051](https://github.com/Mehni/PickUpAndHaul/commit/fd3d0517ddb19708702001641032ff9039f0b04a), [48b96b5](https://github.com/Mehni/PickUpAndHaul/commit/48b96b58f05bb5f67568e4e8c5ced833d654dc44) and [e6c4f19](https://github.com/Mehni/PickUpAndHaul/pull/52/commits/e6c4f19a7eb7a4e0b7d6caf143b03debe8dd5e96)

Minor performance improvements and readability improvements, not much worth mentioning. Most of the custom toils were extracted to their own methods using a simple "Refactor -> Extract Method". A lot of changes, no actual logic change.

---

### [Implement check to verify for invalid containers (ba5735b)](https://github.com/Mehni/PickUpAndHaul/commit/ba5735b9ea679f8b62b9be1fb0112d466faadc63)

This was an attempt by both Bradson and [RadTuna](https://github.com/Mehni/PickUpAndHaul/pull/44) to fix the behavior with Armor Racks (and other containers). Both reached the conclusion that sometimes the found target was not a valid container, and thus needed rechecking. RadTuna tried to mess with the targets, while Bradson found out that the real issue was related to [the logic inside `MakeNewToils` but not inside a toil, causing it to get evaluated too early](https://github.com/Mehni/PickUpAndHaul/blob/master/Source/PickUpAndHaul/JobDriver_UnloadYourHauledInventory.cs#L100-L114).

In Truth, the reason why RadTuna's fix partially worked was because this particular job is started in two locations. [One sets `TargetA` as the pawn itself](https://github.com/Mehni/PickUpAndHaul/blob/master/Source/PickUpAndHaul/PawnUnloadChecker.cs#L6), [the other sets an actual store cell](https://github.com/Mehni/PickUpAndHaul/blob/master/Source/PickUpAndHaul/JobDriver_HaulToInventory.cs#L120). RadTuna changed this to be `TargetB`, thus making us hit the Container part of the code always. However, this made it break in other ways.

Using Bradson's approach, it _worked_, sorta? It had other issues, [like causing every other haul to a shelf to drop the item](https://streamable.com/fbgp7s). This happened because this check considered only containers as valid. Suddenly, no cells were valid for _every other item_, causing the behavior seen in that video.

I ended up discarding this code for these reasons a bit later, but thought about leaving the commit here for historical reasons.

---

### [Reserve destinations inside toils (85c99db)](https://github.com/Mehni/PickUpAndHaul/commit/85c99dbbc34ff3757a7e538ba5d09a0411debb8f)

This is a minor improvement that I am unsure if it is necessary. During testing, I ran into reservation issues at least once:

image

I then imagined the following situation, given the original code (which is identical to Vanilla, which could also have this issue):
```cs
yield return FindTargetOrDrop(carriedThings);
yield return Toils_Reserve.Reserve(TargetIndex.B);
yield return PullItemFromInventory(carriedThings, begin);
yield return VerifyContainerValidOrFindNew();
```

Imagine this:
- Pawn 1 finds target on cell 1, 1, sets it to TargetB, end toil.
- Pawn 2 finds target on cell 1, 1, sets it to TargetB,  end toil.
- Next tick
- Pawn 1 reserves targetB, reserving cell 1, 1
- Pawn 2 tries to reserve targetB, which is cell 1, 1, fail.

I am unsure how "concurrent" the toils are, but it's not unreasonable to think that, while for _most_ things taking 1 tick to reserve a target is no issue, since PU&H finds targets dynamically this can lead to the entire job getting cancelled for no reason. As such, I reserve the target immediately upon finding it, or give up. No reason to leave it up to chance that another pawn might reserve it!

While I was only able to reproduce this issue a handful of times in MANY hours of testing, I did not encounter it again after this minor change. It could be completely unnecessary, and if you prefer removing it, it's quite simple to undo.

#### Update

Bradson did some looking into how toils are run and whether or not they are concurrent, these are his findings 
> I've now looked into the concurrency issue. Toils generally run whenever `jobdriver.ReadyForNextToil()` gets called. This does happen once per tick per pawn within `jobdriver.DriverTick()`, but various vanilla drivers seemingly also do this within specific toils to immediately start the next and not run into this concurrency issue. ilSpy shows 51 used by results for `ReadyForNextToil`. Additionally there's `Toils_General.DoAtomic(action)` which sets a public `tail.atomicWithPrevious` flag to true to allow a toil to run while a pawn is considered `FullBodyBusy`, probably because of toils. `Toils_Reserve.Reserve` does have this flag set to true too. `jobdriver.TryActuallyStartNextToil()`, which actually starts every toil like its name implies, checks for this atomicity flag in a `CanStartNextToilInBusyStance` property and returns early if the check fails. Later on, after successfully running a toil, it does a `defaultCompleteMode == ToilCompleteMod.Instant` check where it decides whether to chain another toil immediately or not. This Instant flag is set by default, our `FindTargetOrDrop` method doesn't touch it or add any tickAction, so it frankly should've been atomic as far as I can tell. We do have an instant toil followed by an `atomicWithPrevious` toil in our pair of find and reserve

So it seems this is not an issue, at all. I was going to undo this change, however, there's still reason for us to do this: we can drop the item if we fail to reserve it, otherwise we'll keep carrying it around. I'm not sure which behavior is best and this is unlikely to happen frequently, so I'm not sure we should even worry about it.

---

### [Add debug messages to drop actions (e30799c)](https://github.com/Mehni/PickUpAndHaul/commit/e30799c973e41a6e39d559f92feb45f885138bdc)

Pawns were dropping items, that was an issue. It made sense to add extra logging here. Actually helped me reach the final debug. If it's too spammy, can be easily removed.

---

### [Rewrite find target logic to handle containers (a32b961)](https://github.com/Mehni/PickUpAndHaul/commit/a32b961e9b543de10ed1d4cac77c5248366cf54c)

The big change, the big fix.

Turns out, we were using `TryFindStoreCellNearColonyDesperate` all along. As this method implies, it actually only finds... Cells. Not containers. Under the hood, it calls `TryFindBestBetterStoreCellFor` and then, if that fails, expands a search radius and tries to haul the item to the nearest available spot. This is very much like the Vanilla `UnloadYourInventory` Job.

What hinted me was that both Bradson and RadTuna used `TryFindBestBetterNonSlotGroupStorageFor`, which finds containers. But only containers. This is much like the Vanilla `HaulToContainer` job.

Then it hit me. We do _both_. So we must consider both containers and cells when searching. Thankfully, we have the perfect method for that: `TryFindBestBetterStorageFor`, which calls both `TryFindBestBetterNonSlotGroupStorageFor` and `TryFindBestBetterStoreCellFor`, does some minor checks, and returns the best result, either a cell or a container.

Removing the now unnecessary "Validate container" logic from the previous code, the result was now identical to current PU&H behavior regarding cells, but similarly works for things like Armor Racks and other containers. [The results are seen in this video](https://streamable.com/n59j0m).

Technically, there is a performance hit to performing the searches, but not more than the "validate target" logic and I'd argue that the alternative is a bug, so I feel like we have no choice. I pondered whether or not to try to implement custom logic to search for both, but in the end I decided against it for two reasons:
1. I doubt I could get meaningful performance improvements
2. This way, we are using a Vanilla method. If Vanilla changes, seemingly this method will be updated with it and we will stay working perfectly fine.

---

### [Update assemblies for new patch (215dec8)](https://github.com/Mehni/PickUpAndHaul/pull/52/commits/215dec83ab8c6cd58cfc4564762b11311e3a514c)

I tried using Git LFS, you know? GitHub doesn't let you use LFS on forks of projects without LFS, it's quite stupid. You should probably recompile these yourself.

## Conclusion

This was... a doozy for me. This was my first time really diving into modding and having to return to good old "gotos" for logic was... Strange.

I must really thank you, @Mehni, for the time, @bbradson and @RadTuna for the help and patience. And sorry for the massive PR and explanations, but I felt like it was a learning experience.

I'd request that, when you have time, try to test this change. I did as much as I could and detect no issues that PU&H doesn't already have (more below), but then again I haven't been testing this mod for as long as you folks have. Maybe you'll find an issue that I haven't. I'm happy to continue helping if needed.

# Outstanding issues

While testing, there are two big issues that are quite obvious and easy to diagnose:

1. While picking up items to haul, we reserve the targets. But then, we drop the reservation because technically we run two jobs. This causes pawns to give up a few times because their target is no longer valid. This is mostly fine and doesn't happen very frequently, and I feel like a fix would require major changes to both the Pick up and Drop code.
2. Hauling to items like Armor Racks only hauls one item at once. This one is quite simple. PU&H tracks the capacity of its targets. Armor Racks has a capacity of 1... For _each item type_. So when we ask it "How many of this (pants) can we store?" it rightfully answers "1" and we consider it full after picking up said pants. But in truth, it can still store a helmet and a shirt, maybe more! Changing this would require a big overhaul of the tracking and I feel like putting this fix out first is much better. Hauling 1 item at a time is infinitely better than the drop and pick up loop from before.

### CODE REVIEW

**Comment by Mehni** [comment]
Thank you very much for your efforts and patience! You've definitely made an improvement to PUAH and I am very grateful to you

**Comment by GoldenBadger** [comment]
Hi, I believe this PR introduces a performance issue. There is fairly constant stutter, with freezes of <=1 second every few seconds, that started suddenly, coinciding with the latest release of this mod. I think one or more of the function calls in this PR is unintentionally blocking.

**Comment by Angelin01** [comment]
@GoldenBadger The main change from this PR is the replacement of a `StoreUtility.TryFindStoreCellNearColonyDesperate` with a `StoreUtility.TryFindBestBetterStorageFor` (and a logic fix), both of which are Vanilla methods used for finding storage cells. While `StoreUtility.TryFindBestBetterStorageFor` is indeed worse performance wise, it shouldn't cause actual stuttering unless you are running a _large_ amount of pawns with a large amount of hauling jobs, or using a map with a large amount of available storage.

I tried to reproduce the stutters, but I am really not seeing it, even with a massive amount of haul jobs.

image

I have been playing for about 2 weeks now, using the fix, with no stutters, but I also don't know your save situation. Can I recommend you open a separate issue? I'll take a look at it. And, if you're willing, can you use [Dubs Performance Analyzer](https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626) so we can try to track what is causing the stutters on your game?

**Comment by GoldenBadger** [comment]
I went to create a new issue with some Dubs Performance Analyzer info attached, but when I went to profile my game I couldn't replicate the stutter. The only thing that changed was I disabled this mod, played for a bit, and then re-enabled it. Looking at the analyser, there aren't many calls to this mod's methods so now I'm fairly confident there are no issues. I'm quite confused now but I suppose everything worked out. Will let you know if I encounter anything else.

Here's my modlist if you're curious: https://pastebin.com/ZgRvgbSA.

**Comment by Angelin01** [comment]
@GoldenBadger Yeah, I don't see anything that alters the hauling jobs there. Maybe it was a coincidence that solved itself between the mod removal, restart and etc. Or Rocketman's cache refresh? Or some weird interaction with Deep Storage? I'm unsure. Either way, I'm glad it's working fine. If it happens again, feel free to open the issue and @ me (I don't believe Mehni is very active anymore) or find me in the Rimworld Discord and I'll poke around.

**Comment by GoldenBadger** [comment]
Thanks!

**Pull request merged**
